# Site settings
title: "Jay Murphy | The Modern Craftsman"
description: "Joseph (Jay) Murphy software developer resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Jay Murphy"
resume_title:                   "Lead Web Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "contact@jmurphy.us"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "901-834-0414"
resume_contact_address:         "3279 Central Ave. Memphis, TN"

resume_header_contact_info:     "3279 Central Ave. Memphis, TN • 901-834-0414 • contact@jmurphy.us"
display_header_contact_info:    "false"

resume_header_intro: "<p>Software developer in Memphis, TN with a passion for web services and architecture. </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jmurphy45"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jmurphyiii/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://jmurphy.us"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
